name = "art-room-web"
compatibility_date = "2026-09-04"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "art-room-db"
database_id = "a6a5cb12-3c61-4927-9ba5-1ee7e9ce7e4b"
